services:

  web:
    image: nginx:latest
    container_name: web-host
    ports:
      - "80:80"        # original
      - "50080:80"     # mirrored
    restart: always

  syslog:
    image: balabit/syslog-ng:latest
    container_name: syslog-host
    ports:
      - "514:514/udp"       # original
      - "50514:514/udp"     # mirrored
    restart: always

  dns:
    image: sameersbn/bind:latest
    container_name: dns-host
    ports:
      - "53:53/udp"         # original
      - "53:53/tcp"
      - "50053:53/udp"      # mirrored
      - "50053:53/tcp"
    environment:
      - BIND_USER=root
    restart: always

  speedtest:
    image: ghcr.io/librespeed/speedtest:latest
    container_name: speedtest-host
    ports:
      - "80:80"         # original
      - "50880:80"      # mirrored
    restart: always

  ftp:
    image: fauria/vsftpd
    container_name: ftp-host
    ports:
      - "21:21"                        # original control
      - "50021:21"                     # mirrored control
      - "21100-21110:21100-21110"     # passive data ports (same both sides)
    environment:
      - FTP_USER=user
      - FTP_PASS=pass
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    restart: always

  snmp:
    image: really/snmpd
    container_name: snmp-host
    ports:
      - "161:161/udp"       # original
      - "50161:161/udp"     # mirrored
    environment:
      - SNMP_COMMUNITY=public
    restart: always

  vpn:
    image: hwdsl2/ipsec-vpn-server
    container_name: vpn-host
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_IPSEC_PSK=your_ipsec_psk
      - VPN_USER=vpnuser
      - VPN_PASSWORD=vpnpass
    ports:
      - "500:500/udp"       # IPsec
      - "4500:4500/udp"
    restart: always
