version: '3.7'

services:

  web:
    image: nginx:latest
    container_name: web-host
    ports:
      - "80:80"
    restart: always

  syslog:
    image: balabit/syslog-ng:latest
    container_name: syslog-host
    ports:
      - "514:514/udp"
    restart: always

  dns:
    image: sameersbn/bind:latest
    container_name: dns-host
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - BIND_USER=root
    restart: always

  speedtest:
    image: ghcr.io/librespeed/speedtest:latest
    container_name: speedtest-host
    ports:
      - "8080:80"
    restart: always

  ftp:
    image: fauria/vsftpd
    container_name: ftp-host
    ports:
      - "21:21"
    environment:
      - FTP_USER=user
      - FTP_PASS=pass
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    restart: always

  snmp:
    image: really/snmpd
    container_name: snmp-host
    network_mode: host
    ports:
      - "161:161/udp"
    environment:
      - SNMP_COMMUNITY=public
    restart: always

  vpn:
    image: hwdsl2/ipsec-vpn-server
    container_name: vpn-host
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_IPSEC_PSK=your_ipsec_psk
      - VPN_USER=vpnuser
      - VPN_PASSWORD=vpnpass
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    restart: always
